/**
 * app.js
 *
 * Adaptador de interfaz de HotelManager. Mantiene navegación y estilos de la
 * SPA original, pero delega reglas financieras y transiciones críticas en
 * hotelService. Los formularios sólo traducen eventos DOM a casos de uso.
 */
import { NAV, STATUS, LABELS, STORES, PAYMENT_METHODS } from './core/constants.js';
import { openDB, all, clearStore } from './database/db.js';
import { repos, createReservation, recordPayment, doCheckin, doCheckout, markReady, setMaintenance, staySummary } from './services/hotelService.js';
import { exportBackup, importBackup, exportCsv } from './services/backupService.js';
import { badge, empty, modal, toast } from './components/ui.js';
import { money, esc } from './utils/formatters.js';
import { today, nights, dateLabel } from './utils/dates.js';

const app = document.querySelector('#app');
let page = location.hash.slice(1) || 'dashboard';
let state = {};
let processing = false;

async function load() {
  const entries = await Promise.all(STORES.map(async (store) => [store, await all(store)]));
  state = Object.fromEntries(entries);
}
const roomTypeName = (id) => state.roomTypes.find((item) => item.id === id)?.name || 'Sin tipo';
const guestName = (id) => { const guest = state.guests.find((item) => item.id === id); return guest ? guest.firstName + ' ' + guest.lastName : '—'; };
const roomName = (id) => state.rooms.find((item) => item.id === id)?.number || '—';
const paid = (reservationId) => state.payments.filter((item) => item.reservationId === reservationId && item.status !== 'VOID').reduce((sum, item) => sum + Number(item.amount), 0);
const pending = (reservation) => Math.max(0, Number(reservation.total) - paid(reservation.id));

function nav() {
  const groups = [['Operación', ['rooms', 'roomTypes', 'guests', 'reservations', 'checkin', 'checkout']], ['Administración', ['payments', 'housekeeping', 'maintenance']], ['Análisis', ['reports']], ['Sistema', ['settings', 'backup']]];
  let html = '<div class="brand"><span class="brand-mark">H</span>HotelManager</div><button class="nav-link" data-action="close-sidebar">☰ Menú</button><button class="nav-link ' + (page === 'dashboard' ? 'active' : '') + '" data-nav="dashboard">▦ <span>Dashboard</span></button>';
  groups.forEach(([group, items]) => { html += '<div class="nav-group">' + group + '</div>'; items.forEach((id) => { const item = NAV.find((entry) => entry[0] === id); html += '<button class="nav-link ' + (page === id ? 'active' : '') + '" data-nav="' + id + '">' + item[2] + ' <span>' + item[1] + '</span></button>'; }); });
  return html;
}
function layout(content) { app.innerHTML = '<div class="shell"><aside class="sidebar" id="sidebar">' + nav() + '</aside><main class="main"><header class="topbar"><button class="btn mobile-menu" data-action="open-sidebar">☰</button><div class="muted">' + (state.settings[0]?.name || 'Configura tu hotel') + '</div><div class="row"><span class="muted hide-mobile">Recepción</span><span class="badge badge-info">Local</span></div></header><section class="content">' + content + '</section></main></div>'; }
function head(title, subtitle, action) { return '<div class="page-head"><div><h1>' + title + '</h1><p class="muted" style="margin-top:7px">' + subtitle + '</p></div>' + (action || '') + '</div>'; }
async function render() { await load(); if (!state.settings.length && page !== 'settings') { renderSetup(); return; } const pages = { dashboard, rooms, roomTypes, guests, reservations, checkin, checkout, payments, housekeeping, maintenance, reports, settings, backup }; layout(await (pages[page] || dashboard)()); }
function renderSetup() { app.innerHTML = '<main style="min-height:100vh;display:grid;place-items:center;padding:20px"><div class="card" style="width:min(520px,100%)"><div class="brand" style="padding:0 0 24px;color:var(--text)"><span class="brand-mark">H</span>HotelManager</div><h1>Bienvenido a HotelManager</h1><p class="muted" style="margin:8px 0 22px">Configure los datos básicos de su hotel para comenzar.</p><form id="setup-form" class="stack"><div class="field"><label>Nombre del hotel *</label><input class="input" name="name" required autofocus></div><div class="field"><label>Dirección</label><input class="input" name="address"></div><div class="form-grid"><div class="field"><label>Teléfono</label><input class="input" name="phone"></div><div class="field"><label>Email</label><input class="input" type="email" name="email"></div></div><div class="field"><label>Moneda</label><select class="select" name="currency"><option>ARS</option><option>USD</option><option>EUR</option></select></div><button class="btn btn-primary">Comenzar</button><button type="button" class="btn" data-action="demo">Cargar datos de demostración</button></form></div></main>'; }
function tablePage(title, subtitle, action, headers, rows) { return head(title, subtitle, '<button class="btn btn-primary" data-action="' + action + '">+ Nuevo</button>') + '<div class="card"><div class="toolbar" style="margin-bottom:14px"><input class="input" style="max-width:300px" placeholder="Buscar..." data-search></div>' + (rows.length ? '<div class="table-wrap"><table class="data-table"><thead><tr>' + headers.map((h) => '<th>' + h + '</th>').join('') + '</tr></thead><tbody>' + rows.join('') + '</tbody></table></div>' : empty('No hay registros', 'Todavía no existen datos registrados.')) + '</div>'; }
async function dashboard() { const rooms = state.rooms, reservations = state.reservations, income = state.payments.reduce((s, p) => s + Number(p.amount), 0), due = reservations.filter((r) => !['finished', 'cancelled', 'no-show'].includes(r.status)).reduce((s, r) => s + pending(r), 0); const count = (status) => rooms.filter((r) => r.status === status).length; const todayReservations = reservations.filter((r) => r.checkIn === today()); const cards = [['Habitaciones totales', rooms.length, '▤'], ['Disponibles', count('available'), '✓'], ['Ocupadas', count('occupied'), '●'], ['Reservadas', count('reserved'), '◷'], ['En limpieza', count('cleaning'), '✦'], ['Mantenimiento', count('maintenance'), '⚒'], ['Check-ins hoy', todayReservations.length, '→'], ['Ingresos registrados', money(income, state.settings[0]?.currency), '$'], ['Pendiente de cobro', money(due, state.settings[0]?.currency), '!']]; return head('Dashboard', 'Resumen operativo de tu hotel', '<button class="btn btn-primary" data-nav="reservations">+ Nueva reserva</button>') + '<div class="grid grid-4">' + cards.map((c) => '<div class="card stat"><div><span class="muted">' + c[0] + '</span><div class="stat-value">' + c[1] + '</div></div><span class="stat-icon">' + c[2] + '</span></div>').join('') + '</div><div class="grid grid-2" style="margin-top:16px"><div class="card"><div class="row between"><h2>Reservas de hoy</h2><button class="btn btn-sm" data-nav="reservations">Ver todas</button></div>' + (todayReservations.length ? '<div class="table-wrap" style="margin-top:12px"><table class="data-table"><thead><tr><th>Huésped</th><th>Habitación</th><th>Entrada</th><th>Estado</th></tr></thead><tbody>' + todayReservations.map((r) => '<tr><td>' + esc(guestName(r.guestId)) + '</td><td>' + roomName(r.roomId) + '</td><td>' + dateLabel(r.checkIn) + '</td><td>' + badge(r.status) + '</td></tr>').join('') + '</tbody></table></div>' : empty('No hay reservas para hoy', 'Las nuevas reservas aparecerán aquí.')) + '</div><div class="card"><h2>Estado de habitaciones</h2><div class="room-grid" style="margin-top:14px">' + (rooms.length ? rooms.map((r) => '<div class="room-tile"><strong>' + esc(r.number) + '</strong><small>' + esc(roomTypeName(r.typeId)) + '</small><div style="margin-top:9px">' + badge(r.status) + '</div></div>').join('') : empty('Sin habitaciones', 'Crea la primera habitación desde el módulo.')) + '</div></div></div>'; }
async function rooms() { return tablePage('Habitaciones', 'Gestiona el inventario y estado de tus habitaciones', 'new-room', ['Número', 'Tipo', 'Piso', 'Capacidad', 'Precio', 'Estado', 'Acciones'], state.rooms.map((r) => '<tr><td><strong>' + esc(r.number) + '</strong></td><td>' + esc(roomTypeName(r.typeId)) + '</td><td>' + esc(r.floor) + '</td><td>' + r.capacity + '</td><td>' + money(r.pricePerNight) + '</td><td>' + badge(r.status) + '</td><td><button class="btn btn-sm" data-action="edit-room" data-id="' + r.id + '">Editar</button></td></tr>')); }
async function roomTypes() { return tablePage('Tipos de habitación', 'Define capacidad y precio base', 'new-room-type', ['Nombre', 'Capacidad', 'Precio base', 'Descripción'], state.roomTypes.map((r) => '<tr><td><strong>' + esc(r.name) + '</strong></td><td>' + r.capacity + '</td><td>' + money(r.basePrice) + '</td><td>' + esc(r.description) + '</td></tr>')); }
async function guests() { return tablePage('Huéspedes', 'Ficha e historial de cada huésped', 'new-guest', ['Nombre', 'Documento', 'Contacto', 'Reservas', 'Acciones'], state.guests.map((g) => '<tr><td><strong>' + esc(g.firstName) + ' ' + esc(g.lastName) + '</strong></td><td>' + esc(g.document) + '</td><td>' + esc(g.email || g.phone || '—') + '</td><td>' + state.reservations.filter((r) => r.guestId === g.id).length + '</td><td><button class="btn btn-sm" data-action="edit-guest" data-id="' + g.id + '">Editar</button></td></tr>')); }
async function reservations() { return tablePage('Reservas', 'Control de reservas y disponibilidad', 'new-reservation', ['Código', 'Huésped', 'Habitación', 'Entrada', 'Salida', 'Total', 'Estado', 'Acciones'], state.reservations.slice().sort((a, b) => a.checkIn.localeCompare(b.checkIn)).map((r) => '<tr><td><strong>' + esc(r.code) + '</strong></td><td>' + esc(guestName(r.guestId)) + '</td><td>' + roomName(r.roomId) + '</td><td>' + dateLabel(r.checkIn) + '</td><td>' + dateLabel(r.checkOut) + '</td><td>' + money(r.total) + '</td><td>' + badge(r.status) + '</td><td>' + (['pending', 'confirmed'].includes(r.status) ? '<button class="btn btn-sm btn-danger" data-action="cancel-reservation" data-id="' + r.id + '">Cancelar</button>' : '') + '</td></tr>')); }
async function checkin() { const rows = state.reservations.filter((r) => ['confirmed', 'pending'].includes(r.status) && r.checkIn <= today() && r.checkOut > today()); return tablePage('Check-in', 'Reserva → resumen → cobro → habitación ocupada', 'new-reservation', ['Código', 'Huésped', 'Habitación', 'Entrada', 'Salida', 'Estado', 'Acciones'], rows.map((r) => '<tr><td>' + esc(r.code) + '</td><td>' + esc(guestName(r.guestId)) + '</td><td>' + roomName(r.roomId) + '</td><td>' + dateLabel(r.checkIn) + '</td><td>' + dateLabel(r.checkOut) + '</td><td>' + badge(r.status) + '</td><td><button class="btn btn-sm btn-primary" data-action="checkin" data-id="' + r.id + '">Ver resumen y cobrar</button></td></tr>')); }
async function checkout() { const rows = state.reservations.filter((r) => r.status === 'checkin'); return tablePage('Check-out', 'Cobra saldo → finaliza estadía → habitación en limpieza', 'new-reservation', ['Huésped', 'Habitación', 'Noches', 'Total', 'Pagado', 'Pendiente', 'Acciones'], rows.map((r) => '<tr><td>' + esc(guestName(r.guestId)) + '</td><td>' + roomName(r.roomId) + '</td><td>' + nights(r.checkIn, r.checkOut) + '</td><td>' + money(r.total) + '</td><td>' + money(paid(r.id)) + '</td><td>' + money(pending(r)) + '</td><td><button class="btn btn-sm btn-primary" data-action="checkout" data-id="' + r.id + '">Ver resumen y finalizar</button></td></tr>')); }
async function payments() { const todayIncome = state.payments.filter((p) => p.date?.slice(0, 10) === today()).reduce((s, p) => s + Number(p.amount), 0); const due = state.reservations.filter((r) => !['finished', 'cancelled', 'no-show'].includes(r.status)).reduce((s, r) => s + pending(r), 0); return head('Pagos', 'Centro financiero: historial, saldos y pagos manuales', '<button class="btn btn-primary" data-action="new-payment">+ Registrar pago</button>') + '<div class="grid grid-4"><div class="card stat"><span class="muted">Total cobrado hoy</span><div class="stat-value">' + money(todayIncome) + '</div></div><div class="card stat"><span class="muted">Total pendiente</span><div class="stat-value">' + money(due) + '</div></div><div class="card stat"><span class="muted">Cantidad de pagos</span><div class="stat-value">' + state.payments.length + '</div></div></div><div class="card" style="margin-top:16px"><div class="table-wrap"><table class="data-table"><thead><tr><th>Reserva</th><th>Huésped</th><th>Habitación</th><th>Fecha</th><th>Monto</th><th>Método</th><th>Origen</th><th>Estado</th></tr></thead><tbody>' + state.payments.slice().sort((a, b) => (b.date || '').localeCompare(a.date || '')).map((p) => { const r = state.reservations.find((x) => x.id === p.reservationId); return '<tr><td>' + esc(r?.code || '—') + '</td><td>' + esc(guestName(p.guestId || r?.guestId)) + '</td><td>' + roomName(r?.roomId) + '</td><td>' + dateLabel(p.date?.slice(0, 10)) + '</td><td>' + money(p.amount) + '</td><td>' + esc(p.method) + '</td><td>' + esc(p.origin || 'MANUAL') + '</td><td>' + badge(p.status || 'PAID') + '</td></tr>'; }).join('') + '</tbody></table></div></div>'; }
async function housekeeping() { const tasks = state.housekeeping.filter((t) => t.status !== 'ready'); return head('Limpieza', 'Habitaciones pendientes después de cada check-out') + '<div class="card">' + (tasks.length ? '<div class="table-wrap"><table class="data-table"><thead><tr><th>Habitación</th><th>Salida</th><th>Estado</th><th></th></tr></thead><tbody>' + tasks.map((t) => '<tr><td>' + roomName(t.roomId) + '</td><td>' + dateLabel(t.at?.slice(0, 10)) + '</td><td>' + badge(t.status) + '</td><td><button class="btn btn-sm btn-primary" data-action="ready-room" data-id="' + t.roomId + '">Marcar como lista</button></td></tr>').join('') + '</tbody></table></div>' : empty('No hay tareas pendientes', 'Las habitaciones enviadas a limpieza aparecerán aquí.')) + '</div>'; }
async function maintenance() { return tablePage('Mantenimiento', 'Bloquea habitaciones y registra el motivo', 'new-maintenance', ['Habitación', 'Motivo', 'Fecha', 'Estado'], state.maintenance.map((m) => '<tr><td>' + roomName(m.roomId) + '</td><td>' + esc(m.motive) + '</td><td>' + dateLabel(m.date) + '</td><td>' + badge(m.status === 'active' ? 'maintenance' : 'ready') + '</td></tr>')); }
async function reports() { const income = state.payments.reduce((s, p) => s + Number(p.amount), 0); return head('Reportes', 'Indicadores calculados desde los datos reales') + '<div class="grid grid-4"><div class="card"><span class="muted">Ingresos registrados</span><div class="stat-value">' + money(income) + '</div></div><div class="card"><span class="muted">Reservas totales</span><div class="stat-value">' + state.reservations.length + '</div></div><div class="card"><span class="muted">Pagos realizados</span><div class="stat-value">' + state.payments.length + '</div></div></div>'; }
async function settings() { const s = state.settings[0] || {}; return head('Configuración', 'Datos generales del hotel') + '<div class="card"><form id="settings-form" class="form-grid"><div class="field"><label>Nombre *</label><input class="input" name="name" required value="' + esc(s.name) + '"></div><div class="field"><label>Moneda</label><select class="select" name="currency"><option>ARS</option><option>USD</option><option>EUR</option></select></div><div class="field full"><label>Dirección</label><input class="input" name="address" value="' + esc(s.address) + '"></div><div class="full"><button class="btn btn-primary">Guardar configuración</button></div></form></div>'; }
async function backup() { return head('Copias de seguridad', 'Exporta o restaura toda la información local') + '<div class="card"><button class="btn btn-primary" data-action="export-backup">Descargar backup JSON</button><input class="input" type="file" accept="application/json" id="backup-file" style="margin-top:12px"><button class="btn" data-action="import-backup">Importar archivo</button></div>'; }

function openForm(action, id) {
  const existing = id ? state.rooms.find((x) => x.id === id) || state.guests.find((x) => x.id === id) : null;
  const body = action.includes('room') ? '<div class="form-grid"><div class="field"><label>Número *</label><input class="input" name="number" required value="' + esc(existing?.number) + '"></div><div class="field"><label>Tipo *</label><select class="select" name="typeId">' + state.roomTypes.map((t) => '<option value="' + t.id + '">' + esc(t.name) + '</option>').join('') + '</select></div><div class="field"><label>Capacidad</label><input class="input" type="number" name="capacity" value="' + (existing?.capacity || 1) + '"></div><div class="field"><label>Precio por noche</label><input class="input" type="number" name="pricePerNight" value="' + (existing?.pricePerNight || 0) + '"></div></div>' : action.includes('guest') ? '<div class="form-grid"><div class="field"><label>Nombre *</label><input class="input" name="firstName" required></div><div class="field"><label>Apellido *</label><input class="input" name="lastName" required></div><div class="field"><label>Documento *</label><input class="input" name="document" required></div><div class="field"><label>Email</label><input class="input" name="email"></div></div>' : action === 'payment' ? '<div class="form-grid"><div class="field full"><label>Reserva *</label><select class="select" name="reservationId">' + state.reservations.filter((r) => !['cancelled', 'finished'].includes(r.status)).map((r) => '<option value="' + r.id + '">' + esc(r.code) + ' — ' + esc(guestName(r.guestId)) + '</option>').join('') + '</select></div><div class="field"><label>Monto *</label><input class="input" type="number" min="1" name="amount" required></div><div class="field"><label>Método</label><select class="select" name="method">' + PAYMENT_METHODS.map((m) => '<option>' + m + '</option>').join('') + '</select></div><div class="field full"><label>Notas</label><input class="input" name="notes"></div></div>' : '<div class="field"><label>Nombre</label><input class="input" name="name" required></div>'; const submit = action === 'payment' ? 'save-payment' : action.includes('guest') ? 'save-guest' : action.includes('room') ? 'save-room' : 'save-generic'; document.body.insertAdjacentHTML('beforeend', modal('Nuevo registro', '<form id="modal-form" data-submit="' + submit + '" data-id="' + (id || '') + '" class="stack">' + body + '<div class="row" style="justify-content:flex-end"><button type="button" class="btn" data-action="close-modal">Cancelar</button><button class="btn btn-primary">Guardar</button></div></form>')); }
function openStayForm(id, checkoutMode) { staySummary(id).then((s) => { const html = '<div class="card"><p>Reserva: <strong>' + esc(s.reservation.code) + '</strong></p><p>Huésped: ' + esc(s.guest.firstName + ' ' + s.guest.lastName) + ' · Habitación: ' + esc(s.room.number) + ' · Noches: ' + s.nights + '</p><p>Total: <strong>' + money(s.reservation.total) + '</strong> · Pagado: <strong>' + money(s.paid) + '</strong> · Pendiente: <strong>' + money(s.pending) + '</strong></p></div><div class="form-grid"><div class="field"><label>Monto a cobrar</label><input class="input" type="number" min="0" max="' + s.pending + '" name="amount" value="' + s.pending + '"></div><div class="field"><label>Método</label><select class="select" name="method">' + PAYMENT_METHODS.map((m) => '<option>' + m + '</option>').join('') + '</select></div>' + (checkoutMode ? '' : '<label class="field full"><input type="checkbox" name="registerPayment" ' + (s.pending > 0 ? 'checked' : '') + '> Registrar pago al realizar check-in</label>') + '<input type="hidden" name="reservationId" value="' + id + '"></div>'; document.body.insertAdjacentHTML('beforeend', modal(checkoutMode ? 'Resumen de check-out' : 'Resumen de estadía', '<form id="modal-form" data-submit="' + (checkoutMode ? 'checkout-stay' : 'checkin-stay') + '" class="stack">' + html + '<div class="row" style="justify-content:flex-end"><button type="button" class="btn" data-action="close-modal">Cancelar</button><button class="btn btn-primary">' + (s.pending > 0 ? (checkoutMode ? 'Registrar pago y finalizar estadía' : 'Confirmar check-in y cobrar') : (checkoutMode ? 'Finalizar estadía' : 'Confirmar check-in')) + '</button></div></form>')); }).catch((error) => toast(error.message, 'error')); }

async function saveForm(formElement) { const data = Object.fromEntries(new FormData(formElement)); const action = formElement.dataset.submit; if (action === 'checkin-stay' || action === 'checkout-stay') { const reservation = state.reservations.find((r) => r.id === data.reservationId); const options = { amount: Number(data.amount || 0), method: data.method, registerPayment: data.registerPayment === 'on' }; if (processing) return; processing = true; const button = formElement.querySelector('button.btn-primary'); button.disabled = true; try { if (action === 'checkin-stay') await doCheckin(data.reservationId, options); else await doCheckout(data.reservationId, options); document.querySelector('#modal')?.remove(); toast('Operación confirmada.', 'success'); await render(); } catch (error) { toast(error.message, 'error'); button.disabled = false; } finally { processing = false; } return; } if (action === 'save-payment') { const reservation = state.reservations.find((r) => r.id === data.reservationId); await recordPayment({ ...data, guestId: reservation?.guestId, amount: Number(data.amount), origin: 'MANUAL' }); document.querySelector('#modal')?.remove(); toast('Pago registrado.', 'success'); await render(); return; } if (action === 'save-guest') await repos.guestsRepo.save(data); else if (action === 'save-room') await repos.roomsRepo.save({ ...data, capacity: Number(data.capacity), pricePerNight: Number(data.pricePerNight), status: 'available' }); document.querySelector('#modal')?.remove(); await render(); }

document.addEventListener('click', async (event) => { const navElement = event.target.closest('[data-nav]'); if (navElement) { page = navElement.dataset.nav; location.hash = page; await render(); return; } const element = event.target.closest('[data-action]'); if (!element) return; const action = element.dataset.action; try { if (action === 'open-sidebar') document.querySelector('#sidebar').classList.add('open'); if (action === 'close-sidebar') document.querySelector('#sidebar').classList.remove('open'); if (action === 'close-modal') document.querySelector('#modal')?.remove(); if (action === 'demo') await demo(); if (action.startsWith('new-')) openForm(action.slice(4)); if (action === 'edit-room' || action === 'edit-guest') openForm(action, element.dataset.id); if (action === 'checkin') openStayForm(element.dataset.id, false); if (action === 'checkout') openStayForm(element.dataset.id, true); if (action === 'ready-room') { await markReady(element.dataset.id); await render(); } if (action === 'cancel-reservation') { const reservation = await repos.reservationsRepo.get(element.dataset.id); await repos.reservationsRepo.save({ ...reservation, status: STATUS.reservation.CANCELLED }); await render(); } if (action === 'export-backup') await exportBackup(); if (action === 'import-backup') { const file = document.querySelector('#backup-file')?.files[0]; if (!file) throw new Error('Selecciona un archivo JSON.'); await importBackup(file); await render(); } } catch (error) { console.error(error); toast(error.message || 'No se pudo completar la operación.', 'error'); } });
document.addEventListener('submit', async (event) => { event.preventDefault(); try { if (event.target.id === 'setup-form' || event.target.id === 'settings-form') { await repos.settingsRepo.save(Object.fromEntries(new FormData(event.target))); page = 'dashboard'; await render(); } else if (event.target.id === 'modal-form') await saveForm(event.target); } catch (error) { console.error(error); toast(error.message, 'error'); } });
async function demo() { for (const store of STORES) await clearStore(store); const type = await repos.roomTypesRepo.save({ name: 'Doble', capacity: 2, basePrice: 65000 }); const room = await repos.roomsRepo.save({ number: '101', typeId: type.id, capacity: 2, pricePerNight: 65000, status: 'available' }); const guest = await repos.guestsRepo.save({ firstName: 'Ana', lastName: 'García', document: '30111222' }); await repos.settingsRepo.save({ name: 'Hotel Aurora', currency: 'ARS' }); await createReservation({ guestId: guest.id, roomId: room.id, checkIn: today(), checkOut: new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10), pricePerNight: 65000, discount: 0 }); await render(); }
openDB().then(render).catch((error) => { console.error(error); app.innerHTML = '<div class="card" style="margin:30px">No se pudo iniciar la base de datos local.</div>'; });
