import {roomTypesRepo,roomsRepo,guestsRepo,reservationsRepo,paymentsRepo,checkInsRepo,checkOutsRepo,housekeepingRepo,maintenanceRepo,settingsRepo} from '../database/repositories/index.js'; import {STATUS} from '../core/constants.js'; import {overlaps,nights,today} from '../utils/dates.js'; import {required,validDates,positive} from '../utils/validators.js';
export const repos={roomTypesRepo,roomsRepo,guestsRepo,reservationsRepo,paymentsRepo,checkInsRepo,checkOutsRepo,housekeepingRepo,maintenanceRepo,settingsRepo};
export async function availability(from,to,capacity,typeId){validDates(from,to);const [rooms,reservations]=await Promise.all([roomsRepo.list(),reservationsRepo.list()]);return rooms.filter(r=>r.capacity>=Number(capacity||0)&&(!typeId||r.typeId===typeId)&&![STATUS.room.MAINTENANCE,STATUS.room.CLEANING,STATUS.room.OCCUPIED].includes(r.status)&&!reservations.some(x=>x.roomId===r.id&&!['cancelled','finished','no-show'].includes(x.status)&&overlaps(from,to,x.checkIn,x.checkOut)))}
export async function createReservation(data){required(data.guestId,'El huésped');required(data.roomId,'La habitación');validDates(data.checkIn,data.checkOut);positive(data.discount,'El descuento');const current=await reservationsRepo.list();if(current.some(x=>x.roomId===data.roomId&&!['cancelled','finished','no-show'].includes(x.status)&&overlaps(data.checkIn,data.checkOut,x.checkIn,x.checkOut)))throw Error('La habitación ya está reservada en esas fechas.');const total=Math.max(0,nights(data.checkIn,data.checkOut)*Number(data.pricePerNight)-Number(data.discount||0));const reservation=await reservationsRepo.save({...data,code:`HM-${Date.now().toString().slice(-6)}`,total,status:data.status||STATUS.reservation.CONFIRMED});if(reservation.status===STATUS.reservation.CONFIRMED)await roomsRepo.save({...await roomsRepo.get(data.roomId),status:STATUS.room.RESERVED});return reservation}
export async function recordPayment(data){positive(data.amount,'El monto');const reservation=await reservationsRepo.get(data.reservationId);if(!reservation)throw Error('La reserva no existe.');const payments=await paymentsRepo.list();const paid=payments.filter(p=>p.reservationId===data.reservationId).reduce((s,p)=>s+Number(p.amount),0);if(paid+Number(data.amount)>Number(reservation.total))throw Error('El pago supera el total de la reserva.');return paymentsRepo.save(data)}
export async function doCheckin(reservationId,notes=''){const r=await reservationsRepo.get(reservationId);if(!r||['cancelled','finished'].includes(r.status))throw Error('La reserva no puede realizar check-in.');await reservationsRepo.save({...r,status:STATUS.reservation.CHECKIN});const room=await roomsRepo.get(r.roomId);await roomsRepo.save({...room,status:STATUS.room.OCCUPIED});return checkInsRepo.save({reservationId,date:new Date().toISOString(),notes})}
export async function doCheckout(reservationId,notes=''){const r=await reservationsRepo.get(reservationId);if(!r||r.status!==STATUS.reservation.CHECKIN)throw Error('Solo una reserva en check-in puede finalizarse.');await reservationsRepo.save({...r,status:STATUS.reservation.FINISHED});const room=await roomsRepo.get(r.roomId);await roomsRepo.save({...room,status:STATUS.room.CLEANING});await housekeepingRepo.save({roomId:r.roomId,reservationId,status:STATUS.housekeeping.PENDING,at:new Date().toISOString()});return checkOutsRepo.save({reservationId,date:new Date().toISOString(),notes})}
export async function markReady(roomId){const room=await roomsRepo.get(roomId);if(!room)throw Error('Habitación inexistente.');await roomsRepo.save({...room,status:STATUS.room.AVAILABLE});const tasks=await housekeepingRepo.list();const task=tasks.find(x=>x.roomId===roomId&&x.status!==STATUS.housekeeping.READY);if(task)await housekeepingRepo.save({...task,status:STATUS.housekeeping.READY,completedAt:new Date().toISOString()})}
export async function setMaintenance(roomId,motive){const room=await roomsRepo.get(roomId);if(!room)throw Error('Habitación inexistente.');await roomsRepo.save({...room,status:STATUS.room.MAINTENANCE});return maintenanceRepo.save({roomId,motive,status:'active',date:today()})}
